spring:
  datasource:
    username: root
    password: zs20010918
    url: jdbc:mysql://localhost:3306/nocv?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

#shiro配置路径
shiro:
  anon-urls:
    - /toLogin*
    - /login.html
    - /login/login
    - /login/getCode
    - /css/**
    - /echarts/**
    - /images/**
    - /layui/**
    - /layui_ext/**
    - /js/**
  login-url: /index.html

  log-out-url: /login/logout*
  authc-ulrs:
    - /**

